{% set name = "forcefield-utilities" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/forcefield-utilities/archive/{{ version }}.tar.gz
  sha256: 9d2c3c564b55c75cac8a4b8bac19930bbd84b49d05177f823c3ae3b96210f22e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - foyer
    - gmso
    - pydantic
    - lxml

test:
  imports:
    - forcefield_utilities
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mosdef-hub/forcefield-utilities
  summary: Utility functions and classes necessary to convert xml forcefields to foyer and gmso Forcefields
  description: |
    Utility functions and classes necessary to convert xml forcefields to foyer and gmso Forcefields
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/mosdef-hub/forcefield-utilities
  dev_url: https://github.com/mosdef-hub/forcefield-utilities

extra:
  recipe-maintainers:
    - umesh-timalsina
    - CalCraven
    - justinGilmer
    - daico007
